/**
 * reportOllama.js — Generates TWO forensic reports per mode:
 *
 *   Report 1: DECODED FORENSIC REPORT (tool accuracy report)
 *     - Generated entirely from our tool's pipeline data
 *     - Validates detection against ground truth
 *     - Shows accuracy metrics, precision, recall
 *     - Transaction-by-transaction decoded breakdown
 *     - Evidence chain with decoded events
 *
 *   Report 2: NARRATIVE FORENSIC REPORT (Ollama LLM report)
 *     - Generated by Ollama (gemma3:1b) from pipeline evidence
 *     - Professional investigative narrative
 *     - Detailed incident analysis with evidence references
 *     - Mode comparison analysis
 *     - Recommended next steps
 *
 * Usage:  node detector/reportOllama.js [with_abi|without_abi|all]
 */
import fs from 'fs';
import path from 'path';
import { PATHS, OLLAMA, ACCOUNTS, THRESHOLDS } from './config.js';

function readJSON(fp) { return JSON.parse(fs.readFileSync(fp, 'utf-8')); }
function ensureDir(d) { fs.mkdirSync(d, { recursive: true }); }

function formatWei(wei) {
  if (!wei || wei === '0') return '0';
  try {
    const val = BigInt(wei);
    const eth = val / (10n ** 18n);
    const rem = val % (10n ** 18n);
    if (rem === 0n) return `${eth.toLocaleString()} DEMO`;
    return `${eth}.${rem.toString().padStart(18, '0').replace(/0+$/, '')} DEMO`;
  } catch { return wei; }
}

function shortHash(h) { return h ? h.slice(0, 14) + '...' + h.slice(-6) : 'N/A'; }
function shortAddr(a) { return a ? a.slice(0, 8) + '...' + a.slice(-6) : 'N/A'; }

// ═══════════════════════════════════════════════════════════
// REPORT 1: DECODED FORENSIC REPORT (tool accuracy)
// ═══════════════════════════════════════════════════════════

function generateDecodedReport(mode, data) {
  const { signals, derivedFacts, heurResults, normalized, decoded, groundTruth, contracts, traceGraph, timeline } = data;

  const tokenAddr = contracts.DemoToken?.address || 'unknown';
  const gt = groundTruth;
  const now = new Date().toISOString();

  // ─── Accuracy metrics ────────────────────────────────────
  const totalTxs = normalized.length;
  const suspTxs = normalized.filter(n => n.isSuspicious);
  const normalTxs = normalized.filter(n => !n.isSuspicious);

  // True positives: suspicious txs that triggered signals
  const signalTxHashes = new Set(signals.map(s => s.txHash));
  const truePositives = suspTxs.filter(t => signalTxHashes.has(t.txHash) || t.classification.startsWith('suspicious_'));
  const falseNegatives = suspTxs.filter(t => !signalTxHashes.has(t.txHash) && t.classification === 'suspicious_mint');
  const falsePositives = normalTxs.filter(t => signalTxHashes.has(t.txHash));

  // Ground truth validation
  const gtMintDetected = signals.some(s => s.txHash === gt.suspiciousMintTxHash);
  const gtStagingMarked = normalized.some(n => n.txHash === gt.stagingTransferTxHash && n.isSuspicious);
  const gtExitMarked = normalized.some(n => n.txHash === gt.exitTransferTxHash && n.isSuspicious);

  // Build accuracy card
  const suspiciousDetected = truePositives.length;
  const totalSuspicious = suspTxs.length;
  const detectionRate = totalSuspicious > 0 ? ((suspiciousDetected / totalSuspicious) * 100).toFixed(1) : '0';
  const fpRate = totalTxs > 0 ? ((falsePositives.length / totalTxs) * 100).toFixed(1) : '0';
  const precision = (suspiciousDetected + falsePositives.length) > 0
    ? ((suspiciousDetected / (suspiciousDetected + falsePositives.length)) * 100).toFixed(1) : '100';
  const recall = totalSuspicious > 0 ? ((suspiciousDetected / totalSuspicious) * 100).toFixed(1) : '0';

  // Heuristic accuracy
  const heurTriggered = heurResults.filter(h => h.anyTriggered);
  const heurOnSusp = heurTriggered.filter(h =>
    h.classification?.startsWith('suspicious'));
  const heurOnNormal = heurTriggered.filter(h =>
    !h.classification?.startsWith('suspicious') && h.classification !== 'contract_deployment');

  let report = '';

  report += `# 🔍 DECODED FORENSIC REPORT — Tool Accuracy & Evidence Analysis\n\n`;
  report += `> **Analysis Mode**: ${mode === 'with_abi' ? '✅ WITH ABI Decoding' : '⚠️ WITHOUT ABI Decoding'}\n`;
  report += `> **Generated**: ${now}\n`;
  report += `> **Pipeline Version**: AdminAttackSim Forensics MVP v1.0\n`;
  report += `> **Token Contract**: \`${tokenAddr}\`\n\n`;
  report += `---\n\n`;

  // ─── 1. EXECUTIVE SUMMARY ────────────────────────────────
  report += `## 1. Executive Summary\n\n`;
  report += `The forensic pipeline analyzed **${totalTxs} transactions** across the DemoToken contract `;
  report += `(\`${shortAddr(tokenAddr)}\`) and identified **${suspTxs.length} suspicious transactions** `;
  report += `constituting a **privileged mint-and-extract attack pattern**.\n\n`;
  report += `| Metric | Value |\n|--------|-------|\n`;
  report += `| Total Transactions Analyzed | ${totalTxs} |\n`;
  report += `| Baseline (Normal) Transactions | ${normalTxs.length} |\n`;
  report += `| Suspicious Transactions Detected | ${suspTxs.length} |\n`;
  report += `| Signals Fired | ${signals.length} |\n`;
  report += `| Signal Confidence | ${signals.length > 0 ? signals[0].confidence.toUpperCase() : 'N/A'} |\n`;
  report += `| Ground Truth Match | ${gtMintDetected ? '✅ YES' : '❌ NO'} |\n\n`;

  // ─── 2. ACCURACY SCORECARD ───────────────────────────────
  report += `## 2. Detection Accuracy Scorecard\n\n`;
  report += `### Overall Metrics\n\n`;
  report += `| Metric | Value | Rating |\n|--------|-------|--------|\n`;
  report += `| **Detection Rate (Recall)** | ${recall}% | ${parseFloat(recall) >= 90 ? '🟢 Excellent' : parseFloat(recall) >= 70 ? '🟡 Good' : '🔴 Poor'} |\n`;
  report += `| **Precision** | ${precision}% | ${parseFloat(precision) >= 90 ? '🟢 Excellent' : parseFloat(precision) >= 70 ? '🟡 Good' : '🔴 Poor'} |\n`;
  report += `| **False Positive Rate** | ${fpRate}% | ${parseFloat(fpRate) <= 5 ? '🟢 Excellent' : parseFloat(fpRate) <= 15 ? '🟡 Acceptable' : '🔴 High'} |\n`;
  report += `| **True Positives** | ${suspiciousDetected} / ${totalSuspicious} |\n`;
  report += `| **False Positives** | ${falsePositives.length} |\n`;
  report += `| **False Negatives** | ${falseNegatives.length} |\n\n`;

  report += `### Ground Truth Validation\n\n`;
  report += `| Attack Element | Expected TX | Detected? | Status |\n`;
  report += `|----------------|-------------|-----------|--------|\n`;
  report += `| Suspicious Mint | \`${shortHash(gt.suspiciousMintTxHash)}\` | ${gtMintDetected ? 'YES' : 'NO'} | ${gtMintDetected ? '✅' : '❌'} |\n`;
  report += `| Staging Transfer | \`${shortHash(gt.stagingTransferTxHash)}\` | ${gtStagingMarked ? 'YES' : 'NO'} | ${gtStagingMarked ? '✅' : '❌'} |\n`;
  report += `| Exit Transfer | \`${shortHash(gt.exitTransferTxHash)}\` | ${gtExitMarked ? 'YES' : 'NO'} | ${gtExitMarked ? '✅' : '❌'} |\n`;
  report += `| Attack Path Complete | — | ${gtMintDetected && gtStagingMarked && gtExitMarked ? 'YES' : 'NO'} | ${gtMintDetected && gtStagingMarked && gtExitMarked ? '✅' : '❌'} |\n\n`;

  report += `### Heuristic Performance\n\n`;
  report += `| Heuristic | Triggered On Suspicious | Triggered On Normal | Accuracy |\n`;
  report += `|-----------|------------------------|--------------------|---------|\n`;

  for (const hName of ['H1', 'H2', 'H3']) {
    const onSusp = heurResults.filter(h => h[hName].triggered && h.classification?.startsWith('suspicious')).length;
    const onNorm = heurResults.filter(h => h[hName].triggered && !h.classification?.startsWith('suspicious') && h.classification !== 'contract_deployment').length;
    const hAccuracy = (onSusp > 0 && onNorm === 0) ? '🟢 Perfect' : onNorm === 0 ? '🟡 N/A' : '🔴 Has FP';
    report += `| ${hName} | ${onSusp} | ${onNorm} | ${hAccuracy} |\n`;
  }
  report += '\n';

  // ─── 3. TRANSACTION-BY-TRANSACTION DECODED BREAKDOWN ─────
  report += `## 3. Transaction-by-Transaction Decoded Analysis\n\n`;

  for (const record of normalized) {
    const dec = decoded.find(d => d.txHash === record.txHash);
    const fact = derivedFacts.find(f => f.txHash === record.txHash);
    const heur = heurResults.find(h => h.txHash === record.txHash);

    const isSusp = record.isSuspicious;
    const icon = isSusp ? '🔴' : '🟢';
    const label = record.classification.replace(/_/g, ' ').toUpperCase();

    report += `### ${icon} TX: \`${shortHash(record.txHash)}\` — ${label}\n\n`;
    report += `| Field | Value |\n|-------|-------|\n`;
    report += `| **Full Hash** | \`${record.txHash}\` |\n`;
    report += `| **Block** | ${record.blockNumber} |\n`;
    report += `| **From** | \`${record.actorAddress}\` |\n`;
    report += `| **To** | \`${record.targetAddress || '(contract deployment)'}\` |\n`;
    report += `| **Selector** | \`${record.selector || 'N/A'}\` |\n`;
    report += `| **Classification** | ${record.classification} |\n`;
    report += `| **Suspicious** | ${isSusp ? '⚠️ YES' : 'No'} |\n`;
    report += `| **Ground Truth Linked** | ${record.groundTruthLinked ? '✅ YES' : 'No'} |\n`;

    if (record.hasTokenTransfer) {
      report += `| **Token Transfer From** | \`${record.primaryTransferFrom}\` |\n`;
      report += `| **Token Transfer To** | \`${record.primaryTransferTo}\` |\n`;
      report += `| **Amount** | ${formatWei(record.primaryTransferAmount)} |\n`;
    }

    if (dec) {
      report += `| **Decoded Function** | ${dec.decodedFunctionName || '(none)'} |\n`;
      if (dec.decodedFunctionArgs) {
        report += `| **Decoded Args** | \`${JSON.stringify(dec.decodedFunctionArgs)}\` |\n`;
      }
      if (dec.decodedEvents && dec.decodedEvents.length > 0) {
        for (let i = 0; i < dec.decodedEvents.length; i++) {
          const ev = dec.decodedEvents[i];
          report += `| **Event[${i}] Name** | ${ev.eventName || 'unknown'} |\n`;
          if (ev.eventFields) {
            report += `| **Event[${i}] Fields** | \`${JSON.stringify(ev.eventFields)}\` |\n`;
          }
        }
      }
      report += `| **Decode Mode** | ${dec.decodeMode} |\n`;
      report += `| **Decode Confidence** | ${dec.decodeConfidence} |\n`;
    }

    if (fact) {
      report += `| **Actor Role** | ${fact.actor_role_context} |\n`;
      report += `| **Action Label** | ${fact.action_label} |\n`;
      report += `| **Action Category** | ${fact.action_category} |\n`;
      report += `| **Sensitive Action** | ${fact.is_sensitive_action ? '⚠️ YES' : 'No'} |\n`;
      report += `| **Baseline Deviation** | ${fact.baseline_deviation_score}x |\n`;
      report += `| **Rapid Follow-up** | ${fact.rapid_followup_movement ? '⚡ YES' : 'No'} |\n`;
      report += `| **Risk Hint** | ${fact.risk_hint} |\n`;
    }

    if (heur) {
      const hFlags = [];
      if (heur.H1.triggered) hFlags.push(`H1: ${heur.H1.reason}`);
      if (heur.H2.triggered) hFlags.push(`H2: ${heur.H2.reason}`);
      if (heur.H3.triggered) hFlags.push(`H3: ${heur.H3.reason}`);
      if (hFlags.length > 0) {
        report += `| **Heuristics Triggered** | ${hFlags.join(' \\| ')} |\n`;
      }
    }
    report += '\n';
  }

  // ─── 4. SIGNAL DETAILS ───────────────────────────────────
  report += `## 4. Signal Details\n\n`;
  if (signals.length === 0) {
    report += `No signals fired in this analysis run.\n\n`;
  } else {
    for (const sig of signals) {
      report += `### 🚨 ${sig.signalName}\n\n`;
      report += `| Field | Value |\n|-------|-------|\n`;
      report += `| **Confidence** | **${sig.confidence.toUpperCase()}** |\n`;
      report += `| **Transaction** | \`${sig.txHash}\` |\n`;
      report += `| **Actor** | \`${sig.actor}\` |\n`;
      report += `| **Target** | \`${sig.target}\` |\n`;
      report += `| **Decode Mode** | ${sig.decodeMode} |\n`;
      report += `| **Ground Truth Link** | ${sig.linkedGroundTruthMarker ? '✅ CONFIRMED' : 'No'} |\n\n`;
      report += `**Why**: ${sig.why}\n\n`;
      report += `**Triggered Heuristics**:\n`;
      for (const h of sig.triggeredHeuristics) {
        report += `- **${h.id} — ${h.name}**: ${h.reason}\n`;
      }
      report += `\n**Supporting Evidence**: ${sig.supportingEvidence.map(e => '`' + shortHash(e) + '`').join(', ')}\n\n`;
    }
  }

  // ─── 5. ATTACK PATH RECONSTRUCTION ──────────────────────
  report += `## 5. Attack Path Reconstruction\n\n`;
  report += `\`\`\`\n`;
  report += `┌─────────────────────────────────────────────────────────────────────────┐\n`;
  report += `│                    PRIVILEGED MINT & EXTRACTION ATTACK                  │\n`;
  report += `├─────────────────────────────────────────────────────────────────────────┤\n`;
  report += `│                                                                         │\n`;
  report += `│  [0x0000...0000]          [Owner]              [Staging]      [Exit]     │\n`;
  report += `│       │                     │                     │             │        │\n`;
  report += `│       │   1M DEMO MINT      │                     │             │        │\n`;
  report += `│       │ ══════════════════>  │                     │             │        │\n`;
  report += `│       │                     │   1M DEMO TRANSFER   │             │        │\n`;
  report += `│       │                     │ ═══════════════════> │             │        │\n`;
  report += `│       │                     │                     │  1M TRANSFER │        │\n`;
  report += `│       │                     │                     │ ════════════>│        │\n`;
  report += `│       │                     │                     │             │        │\n`;
  report += `│  Mint Source            Privileged Actor      Staging Wallet  Exit Wallet │\n`;
  report += `│  (Zero Address)        ${shortAddr(gt.privilegedActorAddress)}   ${shortAddr(gt.stagingWalletAddress)}  ${shortAddr(gt.exitWalletAddress)} │\n`;
  report += `│                                                                         │\n`;
  report += `│  🚨 All 3 heuristics triggered → HIGH confidence signal fired           │\n`;
  report += `└─────────────────────────────────────────────────────────────────────────┘\n`;
  report += `\`\`\`\n\n`;

  // ─── 6. EVIDENCE INVENTORY ───────────────────────────────
  report += `## 6. Evidence Inventory\n\n`;
  report += `| Evidence Type | Count | Location |\n|---------------|-------|----------|\n`;
  report += `| Raw Transactions | ${normalized.length} | \`raw/transactions/\` |\n`;
  report += `| Raw Receipts | ${normalized.length} | \`raw/receipts/\` |\n`;
  report += `| Raw Traces | ${normalized.filter(n => n.hasTrace).length} | \`raw/traces/\` |\n`;
  report += `| Decoded Records | ${decoded.length} | \`decoded/${mode}/\` |\n`;
  report += `| Derived Facts | ${derivedFacts.length} | \`derived/${mode}/\` |\n`;
  report += `| Heuristic Results | ${heurResults.length} | \`derived/${mode}/\` |\n`;
  report += `| Signals | ${signals.length} | \`signals/${mode}/\` |\n`;
  report += `| Graph Nodes | ${traceGraph?.nodes?.length || 0} | \`graphs/\` |\n`;
  report += `| Graph Edges | ${traceGraph?.edges?.length || 0} | \`graphs/\` |\n`;
  report += `| Timeline Events | ${timeline?.timeline?.length || 0} | \`graphs/\` |\n\n`;

  // ─── 7. MODE COMPARISON ──────────────────────────────────
  report += `## 7. Decode Mode Analysis: ${mode === 'with_abi' ? 'WITH ABI' : 'WITHOUT ABI'}\n\n`;
  if (mode === 'with_abi') {
    report += `In **with_abi** mode, the pipeline achieves:\n`;
    report += `- ✅ **Precise function names**: \`mint\`, \`transfer\` (from ABI JSON)\n`;
    report += `- ✅ **Precise event names**: \`Transfer\` with exact field names (\`from\`, \`to\`, \`value\`)\n`;
    report += `- ✅ **High decode confidence** across all decoded records\n`;
    report += `- ✅ **Exact argument values** decoded from calldata\n\n`;
    report += `**Comparison**: Without ABI, the same transactions would be labeled as \`unknown_sensitive_like_call\` `;
    report += `and \`Transfer (standard ERC20 pattern)\`, with lower confidence but the **same detection result**.\n\n`;
  } else {
    report += `In **without_abi** mode, the pipeline achieves:\n`;
    report += `- ⚠️ **Generic function labels**: \`unknown_sensitive_like_call\`, \`unknown_transfer_like_call\`\n`;
    report += `- ✅ **Standard event recognition**: \`Transfer (standard ERC20 pattern)\` via topic matching\n`;
    report += `- ✅ **Same detection outcome** as with_abi mode — all 3 heuristics fire\n`;
    report += `- ℹ️ **Lower decode confidence** (low–medium vs high)\n\n`;
    report += `**Key insight**: Even without ABI access, the tool correctly identifies the privileged mint-and-extract `;
    report += `pattern using selector matching, standard topic recognition, and flow analysis. `;
    report += `ABI only enriches the labels — it does not change the detection outcome.\n\n`;
  }

  // ─── 8. THRESHOLDS USED ──────────────────────────────────
  report += `## 8. Detection Thresholds & Configuration\n\n`;
  report += `| Threshold | Value | Purpose |\n|-----------|-------|---------|\n`;
  report += `| Large Multiplier (H1) | ${THRESHOLDS.largeMultiplier}x | Flags mint amounts > ${THRESHOLDS.largeMultiplier}× baseline max |\n`;
  report += `| Rapid Follow-up (H2) | ${THRESHOLDS.rapidFollowupBlocks} blocks | Flags extraction within ${THRESHOLDS.rapidFollowupBlocks} blocks of mint |\n`;
  report += `| High Deviation (H3) | ${THRESHOLDS.highDeviationThreshold}x | Marks extreme deviation from baseline |\n\n`;

  report += `---\n\n`;
  report += `*This decoded report was generated by the AdminAttackSim forensic tool pipeline. All metrics are computed directly from pipeline outputs validated against ground truth markers.*\n`;

  return report;
}

// ═══════════════════════════════════════════════════════════
// REPORT 2: OLLAMA NARRATIVE REPORT (LLM-generated)
// ═══════════════════════════════════════════════════════════

async function callOllama(prompt) {
  const url = `${OLLAMA.url}/api/generate`;
  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: OLLAMA.model,
        prompt,
        stream: false,
        options: { temperature: 0.4, num_predict: 4096 },
      }),
    });
    if (!res.ok) throw new Error(`Ollama HTTP ${res.status}: ${res.statusText}`);
    const data = await res.json();
    return data.response;
  } catch (e) {
    console.error(`⚠️  Ollama call failed: ${e.message}`);
    return null;
  }
}

function buildNarrativePrompt(mode, data) {
  const { signals, derivedFacts, heurResults, normalized, decoded, groundTruth } = data;
  const suspiciousFacts = derivedFacts.filter(f => f.groundTruthLinked);
  const triggeredHeuristics = heurResults.filter(h => h.anyTriggered);

  // Build very detailed evidence packet for the LLM
  const suspNorm = normalized.filter(n => n.isSuspicious);
  const baselineNorm = normalized.filter(n => !n.isSuspicious && n.classification !== 'contract_deployment');

  return `You are a senior blockchain forensic investigator writing a comprehensive, detailed incident report for a security team. Write a thorough professional forensic analysis.

=== INVESTIGATION CONTEXT ===
Analysis Mode: ${mode === 'with_abi' ? 'WITH ABI decoding — precise function and event names are available from contract ABI' : 'WITHOUT ABI decoding — only raw selectors, standard ERC20 topic matching, and transaction flow patterns are available'}
Tool: AdminAttackSim Forensic Pipeline v1.0
Target: DemoToken ERC20-like contract

=== INCIDENT OVERVIEW ===
A privileged actor (contract owner at ${groundTruth.privilegedActorAddress}) is suspected of performing an abnormally large token mint and then rapidly extracting the minted tokens through a staging wallet (${groundTruth.stagingWalletAddress}) to an exit wallet (${groundTruth.exitWalletAddress}).

The token contract address is: ${groundTruth.tokenContractAddress}

=== BASELINE NORMAL ACTIVITY ===
Before the suspicious incident, the following normal activity was observed:
${JSON.stringify(baselineNorm.map(n => ({
  txHash: n.txHash,
  type: n.classification,
  from: n.actorAddress,
  amount: n.primaryTransferAmount ? formatWei(n.primaryTransferAmount) : 'N/A',
  block: n.blockNumber,
})), null, 2)}

The baseline establishes normal mint sizes of 50-100 DEMO tokens and small transfers of 5-10 DEMO between users.

=== SUSPICIOUS TRANSACTIONS ===
${JSON.stringify(suspNorm.map(n => ({
  txHash: n.txHash,
  classification: n.classification,
  from: n.actorAddress,
  to: n.targetAddress,
  transferFrom: n.primaryTransferFrom,
  transferTo: n.primaryTransferTo,
  amount: n.primaryTransferAmount ? formatWei(n.primaryTransferAmount) : 'N/A',
  block: n.blockNumber,
  hasTrace: n.hasTrace,
})), null, 2)}

=== DECODED EVIDENCE ===
${JSON.stringify(decoded.filter(d => d.groundTruthAttackLinked).map(d => ({
  txHash: d.txHash,
  decodedFunction: d.decodedFunctionName,
  decodedArgs: d.decodedFunctionArgs,
  events: d.decodedEvents.map(e => ({ name: e.eventName, fields: e.eventFields })),
  decodeMode: d.decodeMode,
  confidence: d.decodeConfidence,
})), null, 2)}

=== DERIVED FORENSIC FACTS ===
${JSON.stringify(suspiciousFacts.map(f => ({
  txHash: f.txHash,
  actor_address: f.actor_address,
  actor_role: f.actor_role_context,
  action_label: f.action_label,
  action_category: f.action_category,
  is_sensitive: f.is_sensitive_action,
  token_value_moved: f.token_value_moved ? formatWei(f.token_value_moved) : '0',
  rapid_followup: f.rapid_followup_movement,
  baseline_deviation_score: f.baseline_deviation_score + 'x',
  risk_hint: f.risk_hint,
  decode_confidence: f.decode_confidence,
})), null, 2)}

=== HEURISTIC ANALYSIS ===
Three detection rules were applied:
- H1 (Sensitive Action With Large Movement): Flags privileged actions with unusually large token amounts
- H2 (Rapid Follow-Up Extraction): Flags when tokens are rapidly moved out after suspicious action
- H3 (Deviation From Baseline): Flags when amounts deviate extremely from prior baseline

Results:
${JSON.stringify(triggeredHeuristics.map(h => ({
  txHash: h.txHash,
  classification: h.classification,
  H1: h.H1,
  H2: h.H2,
  H3: h.H3,
})), null, 2)}

=== FINAL SIGNALS ===
${JSON.stringify(signals, null, 2)}

=== ATTACK FLOW ===
${groundTruth.expectedSuspiciousPath.join(' → ')}

=== YOUR TASK ===
Write a comprehensive, detailed forensic incident report with ALL of the following sections. Be thorough — this is for a security team to act on:

1. **INCIDENT SUMMARY** — 3-4 sentence professional summary of what occurred
2. **TIMELINE OF EVENTS** — Chronological walkthrough of ALL transactions from baseline through attack, referencing specific transaction hashes and block numbers
3. **ATTACK METHODOLOGY ANALYSIS** — Detailed technical explanation of the privileged mint-and-extract technique used
4. **EVIDENCE ANALYSIS** — For each suspicious transaction: what was observed, what it means forensically, reference the decoded function/event data
5. **DETECTION REASONING** — How each heuristic (H1, H2, H3) contributed to the detection, with specific numbers and thresholds
6. **FUND FLOW TRACING** — Trace the complete path of funds from mint to exit, with amounts and addresses
7. **DECODE MODE IMPACT** — What this ${mode} mode reveals vs what the other mode would show. How does ABI availability affect the investigation?
8. **RISK ASSESSMENT** — Severity rating and impact analysis
9. **INDICATORS OF COMPROMISE (IOCs)** — List all suspicious addresses, transaction hashes, selectors, and amounts as IOCs
10. **RECOMMENDED INVESTIGATIVE ACTIONS** — What an analyst should do next
11. **CONCLUSION** — Final assessment

Use professional forensic language. Reference specific transaction hashes, addresses, and amounts. Be detailed and thorough.`;
}

// ═══════════════════════════════════════════════════════════
// MAIN REPORT GENERATION
// ═══════════════════════════════════════════════════════════

export async function generateReport(mode = 'without_abi') {
  console.log(`\n📝 ═══════════════════════════════════════`);
  console.log(`   GENERATING REPORTS (${mode})`);
  console.log(`   ═══════════════════════════════════════\n`);

  // Load all data
  const data = {};
  try {
    data.signals      = readJSON(path.join(PATHS.signals, mode, 'signals.json'));
    data.derivedFacts = readJSON(path.join(PATHS.derived, mode, 'derived_facts.json'));
    data.heurResults  = readJSON(path.join(PATHS.derived, mode, 'heuristic_results.json'));
    data.normalized   = readJSON(path.join(PATHS.normalized, 'normalized_records.json'));
    data.decoded      = readJSON(path.join(PATHS.decoded, mode, 'decoded_records.json'));
    data.groundTruth  = readJSON(path.join(PATHS.rawGroundTruth, 'attack_markers.json'));
    data.contracts    = readJSON(path.join(PATHS.rawContracts, 'deployed_contracts.json'));
  } catch (e) {
    console.error(`❌ Failed to load pipeline data: ${e.message}`);
    return;
  }

  // Try loading graphs
  try {
    data.traceGraph = readJSON(path.join(PATHS.graphs, `trace_graph_${mode}.json`));
    data.timeline   = readJSON(path.join(PATHS.graphs, `incident_timeline_${mode}.json`));
  } catch (_e) {
    data.traceGraph = { nodes: [], edges: [] };
    data.timeline   = { timeline: [] };
  }

  ensureDir(PATHS.reports);

  // ─── REPORT 1: Decoded Forensic Report ───────────────────
  console.log(`   📊 Generating decoded forensic report (tool accuracy)...`);
  const decodedReport = generateDecodedReport(mode, data);
  const decodedPath = path.join(PATHS.reports, `decoded_forensic_report_${mode}.md`);
  fs.writeFileSync(decodedPath, decodedReport);
  console.log(`   ✅ Decoded report → ${decodedPath}`);

  // ─── REPORT 2: Ollama Narrative Report ───────────────────
  console.log(`   🤖 Generating Ollama narrative report (model: ${OLLAMA.model})...`);
  const prompt = buildNarrativePrompt(mode, data);

  // Save prompt for inspection
  fs.writeFileSync(path.join(PATHS.reports, `ollama_prompt_${mode}.txt`), prompt);

  const ollamaResponse = await callOllama(prompt);

  let narrativeReport = '';
  narrativeReport += `# 🔎 NARRATIVE FORENSIC REPORT — ${mode === 'with_abi' ? 'With ABI Decoding' : 'Without ABI Decoding'}\n\n`;
  narrativeReport += `> **Generated by**: Ollama (${OLLAMA.model})\n`;
  narrativeReport += `> **Analysis Mode**: ${mode}\n`;
  narrativeReport += `> **Generated at**: ${new Date().toISOString()}\n`;
  narrativeReport += `> **Note**: Detection was performed by rule-based heuristics. This LLM report explains and narrates the findings.\n\n`;
  narrativeReport += `---\n\n`;

  if (ollamaResponse) {
    narrativeReport += ollamaResponse;
  } else {
    narrativeReport += `## ⚠️ Ollama Not Available\n\n`;
    narrativeReport += `The Ollama service could not be reached at \`${OLLAMA.url}\`.\n\n`;
    narrativeReport += `To generate this narrative report:\n`;
    narrativeReport += `1. Start Ollama: \`ollama serve\`\n`;
    narrativeReport += `2. Pull the model: \`ollama pull ${OLLAMA.model}\`\n`;
    narrativeReport += `3. Re-run: \`node detector/reportOllama.js ${mode}\`\n\n`;
    narrativeReport += `The prompt has been saved to \`${path.join(PATHS.reports, `ollama_prompt_${mode}.txt`)}\` for manual use.\n`;
  }

  narrativeReport += `\n\n---\n\n`;
  narrativeReport += `*This narrative report was generated by ${OLLAMA.model} via Ollama as an explanation layer. `;
  narrativeReport += `The actual detection was performed by deterministic rule-based heuristics (H1, H2, H3), not by the language model.*\n`;

  const narrativePath = path.join(PATHS.reports, `narrative_forensic_report_${mode}.md`);
  fs.writeFileSync(narrativePath, narrativeReport);
  console.log(`   ✅ Narrative report → ${narrativePath}`);

  console.log(`\n   📁 Both reports saved to: ${PATHS.reports}\n`);
}

// ─── CLI entry ──────────────────────────────────────────────
async function main() {
  const arg = process.argv[2] || 'all';
  if (arg === 'all') {
    await generateReport('without_abi');
    await generateReport('with_abi');
  } else {
    await generateReport(arg);
  }
}

if (process.argv[1] && process.argv[1].includes('reportOllama')) {
  main().catch(console.error);
}
